remote_theme: antonostrovsky/tale
twitter_username: argumentmaps
formspree_id: mvowpooe
github_repo: "antonostrovsky/open-yale-death-shelly-kagan"
baseurl: "/open-yale-death-shelly-kagan"

title: Open Yale Courses - Death (PHIL 176). Shelly Kagan

plugins:
  - jekyll-paginate
  - jekyll-remote-theme
  - jekyll-feed
